### ISSUE TITLE
rethinkdb?

### ISSUE THREAD

**Issue by timaschew** [foobert/gc#6]
Was this the repo where you used rethinkdb?
I don't find any of your repos containing something with rethinkdb (anymore).

Just wanted to know: 
did you switch to another DB and what were your issues?

**Comment by foobert** [comment]
My geocaching code is usually where I experiment with stuff, and yes one iteration of this code used rethink in the past. I had to drop it because of performance reasons.

Right now I'm using postgres with JSON + a materialized relational view for fast queries.

In the future I want to try mongo again and maybe even Rethinnk as they now seem to be active again as an FOSS project.
